"""Initial migration

Revision ID: 13ad10938015
Revises: 
Create Date: 2026-03-03 15:48:06.569478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ad10938015'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chave', sa.String(), nullable=False),
    sa.Column('valor', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.create_table('logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('userName', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cpfCnpj', sa.String(), nullable=False),
    sa.Column('property', sa.String(), nullable=False),
    sa.Column('totalArea', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpfCnpj')
    )
    op.create_table('servicos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('basePrice', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('execucoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('producerId', sa.String(), nullable=False),
    sa.Column('producerName', sa.String(), nullable=False),
    sa.Column('serviceId', sa.String(), nullable=False),
    sa.Column('serviceName', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('totalValue', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['producerId'], ['produtores.id'], ),
    sa.ForeignKeyConstraint(['serviceId'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('executionId', sa.String(), nullable=False),
    sa.Column('producerName', sa.String(), nullable=False),
    sa.Column('serviceName', sa.String(), nullable=False),
    sa.Column('dueDate', sa.Date(), nullable=False),
    sa.Column('paymentDate', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['executionId'], ['execucoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamentos')
    op.drop_table('execucoes')
    op.drop_table('usuarios')
    op.drop_table('servicos')
    op.drop_table('produtores')
    op.drop_table('logs')
    op.drop_table('configuracoes')
    # ### end Alembic commands ###
