"""add_soft_delete_to_execucoes

Revision ID: 3bcae838c416
Revises: de84ca8ffea2
Create Date: 2026-03-04 14:27:23.916229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bcae838c416'
down_revision: Union[str, Sequence[str], None] = 'de84ca8ffea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execucoes', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execucoes', 'is_deleted')
    # ### end Alembic commands ###
