"""update_produtor_fields_and_soft_delete

Revision ID: 490bfc2821a3
Revises: 7af980a5509e
Create Date: 2026-03-04 13:46:58.673879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '490bfc2821a3'
down_revision: Union[str, Sequence[str], None] = '7af980a5509e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtores', sa.Column('regiao_referencia', sa.String(), nullable=True))
    op.add_column('produtores', sa.Column('telefone_contato', sa.String(), nullable=True))
    op.add_column('produtores', sa.Column('apelido_produtor', sa.String(), nullable=True))
    op.add_column('produtores', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_column('produtores', 'totalArea')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtores', sa.Column('totalArea', sa.FLOAT(), nullable=False))
    op.drop_column('produtores', 'is_deleted')
    op.drop_column('produtores', 'apelido_produtor')
    op.drop_column('produtores', 'telefone_contato')
    op.drop_column('produtores', 'regiao_referencia')
    # ### end Alembic commands ###
