"""Add dados_anteriores and dados_novos to logs

Revision ID: 519638de12f2
Revises: 3bcae838c416
Create Date: 2026-03-04 15:42:06.784529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519638de12f2'
down_revision: Union[str, Sequence[str], None] = '3bcae838c416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('dados_anteriores', sa.String(), nullable=True))
    op.add_column('logs', sa.Column('dados_novos', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'dados_novos')
    op.drop_column('logs', 'dados_anteriores')
    # ### end Alembic commands ###
