"""Add paidAmount to PagamentoModel

Revision ID: 6ab29e921e22
Revises: 13ad10938015
Create Date: 2026-03-04 10:54:38.344065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab29e921e22'
down_revision: Union[str, Sequence[str], None] = '13ad10938015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagamentos', sa.Column('paidAmount', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagamentos', 'paidAmount')
    # ### end Alembic commands ###
