"""Create TransacaoPagamento table

Revision ID: 7af980a5509e
Revises: 6ab29e921e22
Create Date: 2026-03-04 11:04:33.627743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af980a5509e'
down_revision: Union[str, Sequence[str], None] = '6ab29e921e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacoes_pagamento',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pagamentoId', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['pagamentoId'], ['pagamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacoes_pagamento')
    # ### end Alembic commands ###
