"""refatoracao_ordem_servico_1_n

Revision ID: d18fe3dc1929
Revises: ec519e8eb449
Create Date: 2026-03-25 15:46:48.190406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18fe3dc1929'
down_revision: Union[str, Sequence[str], None] = 'ec519e8eb449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execucoes', sa.Column('solicitacaoId', sa.String(), nullable=False))
    op.add_column('execucoes', sa.Column('valor_unitario', sa.Float(), nullable=False))
    op.add_column('execucoes', sa.Column('operador_maquina', sa.String(), nullable=True))
    op.drop_constraint(None, 'execucoes', type_='foreignkey')
    op.create_foreign_key(None, 'execucoes', 'solicitacoes', ['solicitacaoId'], ['id'])
    op.drop_column('execucoes', 'producerName')
    op.drop_column('execucoes', 'producerId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execucoes', sa.Column('producerId', sa.VARCHAR(), nullable=False))
    op.add_column('execucoes', sa.Column('producerName', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'execucoes', type_='foreignkey')
    op.create_foreign_key(None, 'execucoes', 'produtores', ['producerId'], ['id'])
    op.drop_column('execucoes', 'operador_maquina')
    op.drop_column('execucoes', 'valor_unitario')
    op.drop_column('execucoes', 'solicitacaoId')
    # ### end Alembic commands ###
