"""Add is_deleted to servicos

Revision ID: de84ca8ffea2
Revises: 490bfc2821a3
Create Date: 2026-03-04 14:19:01.647533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de84ca8ffea2'
down_revision: Union[str, Sequence[str], None] = '490bfc2821a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicos', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicos', 'is_deleted')
    # ### end Alembic commands ###
