"""Initial clean

Revision ID: e8a77f7c1805
Revises: 
Create Date: 2026-03-26 18:40:28.480308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8a77f7c1805'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chave', sa.String(), nullable=False),
    sa.Column('valor', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.create_table('logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('userName', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('dados_anteriores', sa.String(), nullable=True),
    sa.Column('dados_novos', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cpfCnpj', sa.String(), nullable=False),
    sa.Column('property', sa.String(), nullable=False),
    sa.Column('regiao_referencia', sa.String(), nullable=True),
    sa.Column('telefone_contato', sa.String(), nullable=True),
    sa.Column('apelido_produtor', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpfCnpj')
    )
    op.create_table('servicos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('basePrice', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('solicitacoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('producerId', sa.String(), nullable=False),
    sa.Column('producerName', sa.String(), nullable=False),
    sa.Column('data_solicitacao', sa.Date(), nullable=False),
    sa.Column('prioridade', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['producerId'], ['produtores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execucoes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('solicitacaoId', sa.String(), nullable=False),
    sa.Column('serviceId', sa.String(), nullable=False),
    sa.Column('serviceName', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('valor_unitario', sa.Float(), nullable=False),
    sa.Column('totalValue', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('operador_maquina', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['serviceId'], ['servicos.id'], ),
    sa.ForeignKeyConstraint(['solicitacaoId'], ['solicitacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('executionId', sa.String(), nullable=False),
    sa.Column('producerName', sa.String(), nullable=False),
    sa.Column('serviceName', sa.String(), nullable=False),
    sa.Column('dueDate', sa.Date(), nullable=False),
    sa.Column('paymentDate', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('paidAmount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['executionId'], ['execucoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacoes_pagamento',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pagamentoId', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['pagamentoId'], ['pagamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacoes_pagamento')
    op.drop_table('pagamentos')
    op.drop_table('execucoes')
    op.drop_table('solicitacoes')
    op.drop_table('usuarios')
    op.drop_table('servicos')
    op.drop_table('produtores')
    op.drop_table('logs')
    op.drop_table('configuracoes')
    # ### end Alembic commands ###
