"""add is_deleted to usuarios

Revision ID: ec519e8eb449
Revises: 519638de12f2
Create Date: 2026-03-05 17:30:56.734780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec519e8eb449'
down_revision: Union[str, Sequence[str], None] = '519638de12f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagamentos', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'is_deleted')
    op.drop_column('pagamentos', 'is_deleted')
    # ### end Alembic commands ###
